version: '3'
services:
    cassandra-node1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cassandra-node1
        environment:
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_DC=se1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch 
        ports:
            - "9042:9042"
        volumes:
            - ./cassandra-node1-data:/var/lib/cassandra

    cassandra-node2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cassandra-node2
        environment:
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_DC=se1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        ports:
            - "9043:9042"
        volumes:
            - ./cassandra-node2-data:/var/lib/cassandra
        depends_on:
            - cassandra-node1 

    cassandra-node3:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cassandra-node3
        environment:
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_DC=se1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        ports:
            - "9044:9042"
        volumes:
            - ./cassandra-node3-data:/var/lib/cassandra
        depends_on:
            - cassandra-node2 
