version: '3'

services:
    cassandra:
        image: cassandra:latest
        container_name: my-cassandra-container
        ports:
            - "9042:9042"
        environment:
            - CASSANDRA_SEEDS=cassandra
            - CASSANDRA_CLUSTER_NAME=MyCluster
        volumes:
            - ./data:/var/lib/cassandra

